version: '3.8'

services:
  userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src/UserService:/app/src/UserService:ro
      - ./src/Shared:/app/src/Shared:ro

  eventservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src/EventService:/app/src/EventService:ro
      - ./src/Shared:/app/src/Shared:ro

  commissionservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src/CommissionService:/app/src/CommissionService:ro
      - ./src/Shared:/app/src/Shared:ro

  walletservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src/WalletService:/app/src/WalletService:ro
      - ./src/Shared:/app/src/Shared:ro